---
# Commands to start on workspace startup
tasks:
  - init: npm install
    name: test project
    command: |
      docker-compose -f docker-compose-mysql.yml up
  - name: pluggable widget
    command: npm run start:amap
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
  - ms-azuretools.vscode-docker
  - github.vscode-pull-request-github
  - eamodio.gitlens
  - ms-python.python
