---
# Commands to start on workspace startup
tasks:
  - name: test project
    init: |
      npm install
      ./node_modules/.bin/lerna run i --scope 'amap'
      chmod +x ./scripts/gitpod/build.sh
      docker pull mysql:5.7
      ./scripts/gitpod/build.sh
      gp sync-done bundle
    command: |
      docker-compose -f docker-compose-mysql.yml up --force-recreate
  - name: pluggable widget
    init: gp sync-await bundle
    command: npm run start:amap
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
  - ms-azuretools.vscode-docker
  - github.vscode-pull-request-github
  - eamodio.gitlens
  - ms-python.python
