version: "2.3"

services:
    mendixapp:
        # image: engalar/widgets-resources-cn:v1.2
        image: mendix/mendix-buildpack:v1.4
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 15s
            retries: 2
            start_period: 10s
            timeout: 3s
        environment:
            ADMIN_PASSWORD: Password1!
            # MXRUNTIME_DatabaseJdbcUrl: mysql://db:3306/mendix
            MXRUNTIME_DatabaseType: MySql
            MXRUNTIME_DatabaseUserName: mendix
            MXRUNTIME_DatabasePassword: mendix
            MXRUNTIME_DatabaseHost: db:3306
            MXRUNTIME_DatabaseName: mendix
            # DATABASE_URL: mysql://mendix:mendix@db:3306/mendix
            LOGGING_CONFIG: '{"*": "TRACE"}'
            # DEBUG_CONTAINER: 'true'
            BUILDPACK_XTRACE: 'true'
        ports:
            - 8080:8080
        links:
            - db
        # restart: always
    db:
        image: mysql:5.7
        environment:
            - MYSQL_USER=mendix
            - MYSQL_PASSWORD=mendix
            - MYSQL_DATABASE=mendix
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3306:3306
